#' Return HTML of table
#'
#' @param x A table object generated by table_format. Note that the return_html argument of table_format must be set to FALSE (default) for this function to work.
#' @param include_css If TRUE, returns inline CSS for table formatting. TRUE by default. This is only returned if return_html is also TRUE
#' @param write If TRUE, write results to the file specified in the path argument. FALSE by default.
#' @param path File path to be written to if write is TRUE. "table.txt" in working directory by default.
#'
#' @return The HTML of the table provided.
#' @export
#' @importFrom data.table fwrite
#' @examples table_format(cars) %>% return_html(write = TRUE, path = "output/Figure1.txt")
return_html <- function(x, include_css = TRUE,
                        write = FALSE, path = "table.txt"){
  res <- as_raw_html(x, inline_css = include_css)

  # Remove any font-family specifications so that table inherits
  # from the website's stylesheet
  res <- gsub("font-family.*?;\\s*", "", res)
  if(write){
    fwrite(list(res), file = path, quote = FALSE)
  } else {
    return(res)
  }
}
